import type { DbState, PlanInputs } from "../domain/types";

const now = new Date().toISOString();

function retentionDate(years: number): string {
  const d = new Date();
  d.setFullYear(d.getFullYear() + years);
  return d.toISOString();
}

const defaultPlanInputs: PlanInputs = {
  profile: {
    currentAge: 40,
    retirementAge: 65,
    lifeExpectancy: 90,
    province: "ON",
  },
  assets: [],
  liabilities: [],
  registered: [
    { type: "RRSP", currentBalance: 150_000, annualContribution: 10_000, growthRatePercent: 5 },
    { type: "TFSA", currentBalance: 50_000, annualContribution: 7_000, growthRatePercent: 5 },
    { type: "FHSA", currentBalance: 0, annualContribution: 0, growthRatePercent: 5 },
  ],
  nonRegistered: [],
  incomeExpense: {
    annualEmploymentIncome: 80_000,
    annualOtherIncome: 0,
    annualEssentialExpenses: 36_000,
    annualDiscretionaryExpenses: 18_000,
    retirementExpenseRatio: 0.8,
  },
  assumptions: {
    inflationRatePercent: 2.5,
    realReturnPercent: 4,
    withdrawalOrder: "RRSP_first",
  },
};

export function seedDbState(): DbState {
  return {
    organizations: [
      {
        id: "org_demo",
        name: "North Maple Advisory",
        createdAt: now,
      },
    ],
    users: [
      {
        id: "user_owner_1",
        organizationId: "org_demo",
        email: "owner@nmaple.ca",
        fullName: "Maya Owner",
        role: "owner",
        active: true,
        createdAt: now,
      },
      {
        id: "user_advisor_1",
        organizationId: "org_demo",
        email: "advisor@nmaple.ca",
        fullName: "Elliot Advisor",
        role: "advisor",
        active: true,
        createdAt: now,
      },
      {
        id: "user_compliance_1",
        organizationId: "org_demo",
        email: "compliance@nmaple.ca",
        fullName: "Jordan Compliance",
        role: "compliance",
        active: true,
        createdAt: now,
      },
      {
        id: "user_client_1",
        organizationId: "org_demo",
        email: "client@example.ca",
        fullName: "Casey Client",
        role: "client",
        active: true,
        createdAt: now,
      },
      {
        id: "user_sysadmin_1",
        organizationId: "org_demo",
        email: "sysadmin@nmaple.ca",
        fullName: "Taylor SysAdmin",
        role: "system_admin",
        active: true,
        createdAt: now,
      },
    ],
    households: [
      {
        id: "household_demo_1",
        organizationId: "org_demo",
        householdName: "Casey Household",
        primaryAdvisorUserId: "user_advisor_1",
        createdAt: now,
      },
    ],
    clients: [
      {
        id: "client_demo_1",
        organizationId: "org_demo",
        householdId: "household_demo_1",
        fullNameMasked: "C*** C*****",
        emailMasked: "c***@example.ca",
        phoneMasked: "***-***-1234",
        addressMasked: "**** Maple Street, Toronto",
        riskProfile: "moderate",
        kycCompleted: true,
        createdAt: now,
      },
    ],
    financialProfiles: [
      {
        id: "profile_demo_1",
        organizationId: "org_demo",
        clientId: "client_demo_1",
        effectiveDate: now,
        inputs: defaultPlanInputs,
        createdByUserId: "user_advisor_1",
        createdAt: now,
      },
    ],
    riskProfileSnapshots: [
      {
        id: "risk_snap_1",
        organizationId: "org_demo",
        clientId: "client_demo_1",
        riskTolerance: "moderate",
        investmentHorizon: "long",
        incomeStability: "stable",
        knowledgeLevel: "intermediate",
        notes: "Initial risk assessment during onboarding.",
        assessedByUserId: "user_advisor_1",
        assessedAt: now,
      },
    ],
    kycSnapshots: [
      {
        id: "kyc_snap_1",
        organizationId: "org_demo",
        clientId: "client_demo_1",
        versionNumber: 1,
        identityVerified: true,
        employmentStatus: "employed_full_time",
        sourceOfFunds: "employment_income",
        politicallyExposed: false,
        sanctionsChecked: true,
        notes: "Initial KYC completed at onboarding.",
        completedByUserId: "user_advisor_1",
        completedAt: now,
      },
    ],
    netWorthRecords: [],
    plans: [],
    planVersions: [],
    scenarios: [],
    recommendationNotes: [],
    disclosureAcceptances: [],
    meetingNotes: [],
    reviewCycles: [],
    auditEvents: [],
    planApprovals: [],
    aiDrafts: [],
    portalSessions: [],
    fdxConsents: [],
    fdxAccessTokens: [],
    fdxOauthClients: [
      {
        clientId: "fdx-demo-client",
        clientSecret: "fdx-demo-secret",
        organizationId: "org_demo",
        name: "FDX Demo TPP",
        redirectUris: ["http://localhost:8787/callback"],
        active: true,
      },
    ],
    fdxAuthorizationCodes: [],
    piiVault: [],
    apiLogs: [],
    notificationTemplates: [
      {
        id: "template_reminder_1",
        organizationId: "org_demo",
        name: "Review Reminder",
        channel: "email",
        subject: "Client review reminder",
        body: "Reminder: {{clientId}} review due on {{date}}",
        active: true,
      },
      {
        id: "template_2fa_1",
        organizationId: "org_demo",
        name: "Two Factor OTP",
        channel: "sms",
        body: "Your verification code is {{otp}}. It expires in 10 minutes.",
        active: true,
      },
      {
        id: "template_consent_expiry",
        organizationId: "org_demo",
        name: "Consent Expiry Alert",
        channel: "email",
        subject: "Data consent expiring soon",
        body: "Consent {{consentId}} for {{clientId}} expires on {{expiryDate}}. Please review.",
        active: true,
      },
      {
        id: "template_suspicious_login",
        organizationId: "org_demo",
        name: "Suspicious Login Alert",
        channel: "email",
        subject: "Unusual login activity detected",
        body: "A login from an unusual location was detected for {{userId}} at {{timestamp}}.",
        active: true,
      },
    ],
    notificationRules: [
      {
        id: "rule_reminder_review",
        organizationId: "org_demo",
        name: "Annual review reminder",
        triggerType: "reminder",
        templateId: "template_reminder_1",
        conditionExpr: "review_due_within_days<=7",
        enabled: true,
        throttleMinutes: 1440,
      },
      {
        id: "rule_consent_expiry",
        organizationId: "org_demo",
        name: "Consent expiry alert",
        triggerType: "consent_expiry",
        templateId: "template_consent_expiry",
        conditionExpr: "consent_expires_within_days<=14",
        enabled: true,
        throttleMinutes: 1440,
      },
    ],
    notificationEvents: [],
    twoFactorChallenges: [],
    controlTickets: [],
    analyticsConfigs: [
      {
        id: "analytics_default",
        organizationId: "org_demo",
        metricDefinitions: [
          {
            key: "client_count",
            label: "Total Clients",
            formula: "count(clients)",
            chartType: "kpi",
          },
          {
            key: "networth_projection_avg",
            label: "Average Final Net Worth",
            formula: "avg(last(planVersions.projections.netWorth))",
            chartType: "line",
          },
        ],
        insightRules: [
          {
            id: "insight_allocation_drift",
            name: "Asset allocation drift > 10%",
            category: "allocation_drift",
            expr: "allocation_drift_pct > 10",
            severity: "warning",
            priority: 10,
          },
          {
            id: "insight_risk_mismatch",
            name: "Risk profile vs. portfolio mismatch",
            category: "risk_mismatch",
            expr: "risk_score_delta > 2",
            severity: "critical",
            priority: 9,
          },
          {
            id: "insight_liquidity",
            name: "Emergency fund below 3 months",
            category: "liquidity_warning",
            expr: "liquid_months < 3",
            severity: "warning",
            priority: 8,
          },
          {
            id: "insight_conflict",
            name: "Undisclosed compensation conflict",
            category: "conflict_of_interest",
            expr: "undisclosed_conflicts > 0",
            severity: "critical",
            priority: 10,
          },
        ],
      },
    ],
    securityPolicies: [
      {
        id: "policy_default",
        organizationId: "org_demo",
        keyVersion: "v1",
        strictTwoEyeActions: ["notification.rule.update", "analytics.config.update"],
        strictFourEyeActions: ["fdx.client.register", "security.policy.update"],
        piiFields: ["userId", "email", "phone", "address", "fullName", "dateOfBirth"],
        logRetentionDays: 2555,
      },
    ],
    clientBankProfiles: [],
    insightAlerts: [],
    conflictDisclosures: [],
    advisorAttestations: [],
    dataRetentionPolicies: [
      {
        id: "retention_client_pii",
        organizationId: "org_demo",
        dataType: "client_pii",
        retentionYears: 7,
        permanent: false,
        lastEnforcedAt: now,
      },
      {
        id: "retention_audit_logs",
        organizationId: "org_demo",
        dataType: "audit_logs",
        retentionYears: 10,
        permanent: false,
        lastEnforcedAt: now,
      },
      {
        id: "retention_consent_logs",
        organizationId: "org_demo",
        dataType: "consent_logs",
        retentionYears: 0,
        permanent: true,
        lastEnforcedAt: now,
      },
      {
        id: "retention_ai_drafts",
        organizationId: "org_demo",
        dataType: "ai_drafts",
        retentionYears: 7,
        permanent: false,
        lastEnforcedAt: now,
      },
    ],
  };
}
